# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-23T08:59:33Z"
  labels:
    app: alpaca
    env: prod
    ver: "1"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:env: {}
          f:ver: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:env: {}
          f:ver: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-04-23T11:38:55Z"
  name: alpaca-prod
  namespace: default
  resourceVersion: "94060"
  selfLink: /api/v1/namespaces/default/services/alpaca-prod
  uid: 70877c0a-8fad-417e-b5d0-c590e6be0d4b
spec:
  clusterIP: 10.97.226.60
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31363
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alpaca
    env: prod
    ver: "1"
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
